### ISSUE TITLE
Not working for Stellaris

### ISSUE THREAD

**Issue by anticitizn** [anticitizn/creamlinux#1]
Continuing this issue here since the upstream repo got archived.

@clamor-s @rednatnas I just tested the latest creamlinux release on Stellaris 3.7.4 with up to date DLCs and it appeared to work fine (the game launched, the DLCs loaded and I could start a campaign). So it appears it was an outdated DLC files issue all along. Please test when you can and see if it works for you.

**Comment by anticitizn** [comment]
Yes, I do have red triangles but the DLCs nevertheless work in-game. If you have Discord, you can send me a friend request (anticitizen#0067). Otherwise send me a message at the e-mail on my github profile page

**Comment by clamor-s** [comment]
@anticitizn @rednatnas I can confirm that issue was in dlc.

**Comment by anticitizn** [comment]
It's confirmed then that outdated DLC files are the culprit.

**Comment by rednatnas** [comment]
> It's confirmed then that outdated DLC files are the culprit.

Thanks I'll try that out!

**Comment by anticitizn** [comment]
@rednatnas I just saw [this issue](https://github.com/20PercentRendered/creamlinux/issues/19). Am I understanding correctly that Stellaris works fine on creamlinux 1.3 even with outdated DLC files?

**Comment by rednatnas** [comment]
> @rednatnas I just saw [this issue](https://github.com/20PercentRendered/creamlinux/issues/19). Am I understanding correctly that Stellaris 3.7.3 works fine on creamlinux 1.3 even with outdated DLC files?

yeah, that's right
