### ISSUE TITLE
wrong ELF class: ELFCLASS32) : ignored 

### ISSUE THREAD

**Issue by tafaaa** [anticitizn/creamlinux#10]
ERROR: ld.so: object '/home/motafa/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/usr/bin/sh: 0: cannot open ./cream.sh: No such file

**Comment by anticitizn** [comment]
What game is this? Can you post a screenshot of your game's directory?

**Comment by tafaaa** [comment]
![Screenshot from 2023-06-10 21-49-07](https://github.com/anticitizn/creamlinux/assets/59757662/91930e4f-bcb5-4d12-be59-ad084cb43b2c)
![Screenshot from 2023-06-10 21-46-51](https://github.com/anticitizn/creamlinux/assets/59757662/820dc377-9f22-4106-99d2-dca0c89dc27c)
Gotham knights is the game

**Comment by anticitizn** [comment]
I suppose you actually put the files in the game's directory now. :P Once you test, can you please let me know if the game does actually work with creamlinux and the DLCs are unlocked?

**Comment by tafaaa** [comment]
sorry for bothering you, the creamlinux launch option command work i can start the game but no dlc still its a plus i can start the game lol

**Comment by anticitizn** [comment]
Don't worry about it, I'm here to help. I can't count the amount of times I forgot to unpack creamlinux or something like that too :)

Do you have the actual physical DLC files in the game? Some games include all the DLC files by default and just need creamlinux to "unlock" them, but for others you need to source the actual DLC files yourself in addition to using creamlinux.

**Comment by anticitizn** [comment]
Also you will in any case have to add the IDs of the DLCs to the file `cream_api.ini`. Since it looks like the game only has 1 DLC, you can just add this to the end of `cream_api.ini`:
`41516930 = Gotham Knights: Visionary Pack`

**Comment by tafaaa** [comment]
i dont have the physical dlc file imma try it tho.

ps: your the best <3

**Comment by filip264CZ9** [comment]
wait i dont get it how did you fix it?
