### ISSUE TITLE
Not working for CK3

### ISSUE THREAD

**Issue by ZhenyaPav** [anticitizn/creamlinux#15]
When I install this on CK3, I get a Steam runtime communication error in the launcher, and ingame the DLC are marked as not purchased.

**Comment by T00fy** [comment]
You can get passed the runtime communication error by using the latest cream.sh from the repo and not from the release.
https://github.com/anticitizn/creamlinux/blob/master/package/cream.sh

But that alone does not get any DLC's to work, they still disabled in the game.
I'm just about to try compile the repo from source and see if that helps. Will report back.

**Comment by T00fy** [comment]
Right, I got it to work now. (Only after enabling the logs in main.cpp and actually seeing what it was doing.) It looks like CK3 has a special directory structure compared to other games

The codes actual working directory for CK3 is where libsteam_api.so is located. So it's expecting the ini file to be in the same place as that file. 

So to get it working:

1. My previous comment still stands. You need cream.sh from the main repo not from the release.
2.  `lib32Creamlinux.so`, `lib64Creamlinux.so` and `cream.sh`  needs to be in the directory steam_games/steamapps/common/Crusader Kings III (i.e. the root directory of where the game is installed on steam)
3. `cream_api.ini` needs to be in team_games/steamapps/common/Crusader Kings III/**binaries**
4. (optional): `cream_api.ini` from the repo is not updated with all the DLC, so you should also append the following to that file:
```
2311920 = Crusader Kings III: Tours and Tournaments
2311930 = Crusader Kings III: Elegance of the Empire
2313541 = Crusader Kings III: Wards and Wardens
2313540 = Crusader Kings III: Legacy of Persia
```

After that it should work.
I feel like cream.sh could (and should) be modified to handle this case for CK3 automatically, so i might make a PR for it later.

**Comment by anticitizn** [comment]
I assume that CK3 works fine after the PR, thanks again for that.
