### ISSUE TITLE
[Feature Request] Unlock All

### ISSUE THREAD

**Issue by LustyWizard1304** [anticitizn/creamlinux#16]
Howdy! Currently the program works flawlessly for most games as long as you manually add the DLC ID to the cream_api.ini file, could you maybe look into adding a "unlock all" function similar to the Original CreamAPI?

**Comment by anticitizn** [comment]
Hey, Novattz's [installation script](https://github.com/Novattz/creamlinux-installer) more or less accomplishes this. It can automatically install creamlinux for any Steam game and fetch an up-to-date list of its DLCs. You do have to rerun it once a new DLC is out, but I think that's already more convenient than before.
