### ISSUE TITLE
My game wouldnt start:(

### ISSUE THREAD

**Issue by filip264CZ9** [anticitizn/creamlinux#19]
hey, after doing everything the post said such as downloading the latest version, unziping the file and copying the files to the game directory and setting the launch options to sh ./cream.sh %command% my game wouldnt start. Ive added chmod +x cream.sh script to the cream.sh file, it still didnt work. Ive also tried to change the launch options to gnome-terminal -- sh -c "./cream.sh %command%; exec bash" but it wouldnt load also btw the console said this: ERROR: ld.so: object '/home/(name)/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
sh: 1: ./cream.sh: Permission denied

but noone of those worked also. And yes i did put the 4 files in the game directory not in any types of subfolders.

im pretty new to linux so sorry if im just stupid and did something wrong

**Comment by anticitizn** [comment]
Hey, all good! Try running `chmod +x ./cream.sh` inside the directory of your game - that should fix it. What game is it, by the way?

**Comment by filip264CZ9** [comment]
Hey, the game is Hearts of iron 4. Also in my original post i said i actually tried putting chmod +x ./cream.sh inside the cream.sh file, then i set my launch options to sh ./cream.sh %command%. today i also tried it withnout the launch options set to sh ./cream.sh %command% and hoi4 started normally so i think it has to do something with the code. I would appreciate it if you could reply again.
![cream sh](https://github.com/anticitizn/creamlinux/assets/157699322/a3baec6b-248d-4b22-b311-8308e8006855)

**Comment by anticitizn** [comment]
Ah, sorry - was quite tired when I read your post. You are supposed to execute `chmod +x ./cream.sh` in a terminal opened in the game's directory, not add it to the script. The reason for this is that for some reason your script doesn't have execution permissions (aka it cannot run) until you manually set them. Example:
![image](https://github.com/anticitizn/creamlinux/assets/33865403/e731793f-8093-47d1-8bfe-021a4558e199)

**Comment by filip264CZ9** [comment]
unfortunetly this did not help at all, after trying this:
![ss](https://github.com/anticitizn/creamlinux/assets/157699322/f05c6604-3985-4633-85b4-920e1f36473a)
and while i had my launch options to `./cream.sh %command%` it was completly the same.
then i tried to put my launch options back to gnome-terminal -- sh -c "./cream.sh %command%; exec bash" it said this: 
![ss1](https://github.com/anticitizn/creamlinux/assets/157699322/a2a391d7-045c-4df1-90ab-9280016c2c83)

again sorry for wasting your time.

**Comment by filip264CZ9** [comment]
also i was wondering if it isnt because im using an older version of mint (20.3) and the newest is 21.3 so i dunno

**Comment by filip264CZ9** [comment]
@anticitizn i was thinking it it isnt because of my pc version or somthing i dunno

**Comment by T00fy** [comment]
Use the latest cream.sh from the repo not from the release.

**Comment by filip264CZ9** [comment]
@anticitizn i know this is a stupid question but i dont really understand github so how do you download the new version? last time i clicked on "latest" in the usage section

**Comment by filip264CZ9** [comment]
@anticitizn well i didnt help much... ![ermmm](https://github.com/anticitizn/creamlinux/assets/157699322/9fb65b23-cfa1-44c7-b85a-09be0f83ac0f)
its saying the exact same thing but now its also saying something like skipping destruction (fork without exec?)
