### ISSUE TITLE
Not working for hoi4

### ISSUE THREAD

**Issue by anticitizn** [anticitizn/creamlinux#2]
Continuing this [issue](https://github.com/20PercentRendered/creamlinux/issues/18) here since the old repo got archived.

@JustCauseWhyNot @Gren-95 are you absolutely sure that your DLC files are up to date? We had an issue with DLCs in Stellaris and it turned out to be because even old DLCs were changed in an unrelated update and the files no longer worked. I don't have the hoi4 files myself to test right now, but I'll try in the coming days.

The log provided in the old issue is completely normal (those errors always pop up), so I suspect DLC files are the ultimate culprit here as well.

**Comment by JustCauseWhyNot** [comment]
I'm using [Hearts of Iron IV_DLC_Pack_Build_10515977](https://drive.google.com/file/d/1YaqskNJficCtzd5DOHqpJoaOsdgCfY6n/view). I believe that's the most up to date one. I also found it funny that I indirectly ended that repo.

**Comment by anticitizn** [comment]
Hi, thanks for the quick response. Please don't post links to downloads here though, I have no idea what GitHub's policy is on these (better safe than sorry). The link also doesn't work at the moment so I can't tell for sure, but since there was a patch a couple of weeks ago and @Gren-95 reported that most of the DLCs work for him, I hope the files are just slightly outdated. Will update you once I can test myself.

**Comment by JustCauseWhyNot** [comment]
Link gone :) . Not sure why it didn't work for you? was it that you couldn't download them? I'll see if I can get more updated files. Those were from feb 16.

**Comment by anticitizn** [comment]
Google said the download quota was exceeded, but no matter. There were two patches since then (one on 01.03 and one on 09.03), so the files are probably indeed outdated.

**Comment by JustCauseWhyNot** [comment]
> Google said the download quota was exceeded

You gotta circumvent them. But it's ok.

I'll try with more updated files.

**Comment by JustCauseWhyNot** [comment]
It still doesn't work after making sure I've got the most updated dlc.

**Comment by anticitizn** [comment]
Got it. I'll test myself when I can get around to downloading the latest files sometime this week, no other ideas for now.

Those errors should be harmless since they pop up in Stellaris where the DLCs work, and even when you disable creamlinux (do just `konsole --hold -e %command%` launch option on any game and you'll usually see similar errors still show up).

**Comment by JustCauseWhyNot** [comment]
In order too bypass the google drive limit you'll need create a folder in  drive with

**Comment by anticitizn** [comment]
I managed to get the exact same files as you and all the DLCs seem to work for me, including By Blood Alone. I could start a campaign and all the DLCs were on.

Just to make sure: you have tried to start a campaign and see if DLC features are enabled, correct? The paradox launcher might display red triangles next to the DLCs, but they still work in-game. Can you try to remove your existing creamlinux files and try again with a clean [download](https://github.com/anticitizn/creamlinux/releases/latest/download/creamlinux.zip)?

Failing that, try to set Launch Options to skip the launcher, then post logs again. For some reason when using the paradox launcher a lot of information gets omitted from the console.
![image](https://user-images.githubusercontent.com/33865403/230042195-b86fd12f-4fd8-427d-b9b5-033285ef9c86.png)

**Comment by Gren-95** [comment]
after redownloading and replacing the creamapi files it worked.
i should have done that first.
Glad to see this project is quite active :)

**Comment by anticitizn** [comment]
Good to hear :) I'll try to keep it active as much as I can

**Comment by JustCauseWhyNot** [comment]
Isn't Switzerland supposed too have a focus tree? The dlc for some reason seems to be working now when it wasn't earlier. I've not done anything but between the last message I sent and now. But other than switzerland not having a focus tree the dlc seems to be working.

**Comment by Gren-95** [comment]
> 

what about ethiopia and the plain focuses?
are they still there?

**Comment by JustCauseWhyNot** [comment]
No ethiopian focuses either.

**Comment by anticitizn** [comment]
Sounds like By Blood Alone isn't working for you. Check if you have the new aircraft designer (most likely not). If the other DLCs work and you haven't updated your creamlinux version in a while, have a look at your `cream_api.ini` and see if By Blood Alone is in there. It does work properly for me as well so I suppose it is something on your end.

**Comment by JustCauseWhyNot** [comment]
You're right it wasn't in the cream_api.ini.

**Comment by anticitizn** [comment]
So all the DLCs appear to be working properly now?

**Comment by anticitizn** [comment]
Everything seems to be working for now so closing the issue.

**Comment by anticitizn** [comment]
All good!
