### ISSUE TITLE
ETS2 not working

### ISSUE THREAD

**Issue by tr0u8le** [anticitizn/creamlinux#20]
`ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 24615 != 24613, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
cp: cannot stat '/home/xxx/.local/share/Steam/steamapps/common/Euro Truck Simulator 2/bin/linux_x64/lib32Creamlinux.so': No such file or directory
Error: Failed to copy /home/xxx/.local/share/Steam/steamapps/common/Euro Truck Simulator 2/bin/linux_x64/lib32Creamlinux.so to /tmp/lib32Creamlinux.so
ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 24619 != 24608, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 24622 != 24608, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
flatpak: symbol lookup error: /lib64/libappstream.so.4: undefined symbol: curl_url_cleanup
pid 24632 != 24608, skipping destruction (fork without exec?)
pid 24630 != 24608, skipping destruction (fork without exec?)
pid 24633 != 24608, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 24636 != 24608, skipping destruction (fork without exec?)
pid 24637 != 24608, skipping destruction (fork without exec?)
pid 24638 != 24608, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 24642 != 24608, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 24641 != 24608, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/xxx/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
`

**Comment by tr0u8le** [comment]
ETS2 i don't have exe

**Comment by anticitizn** [comment]
Hello, please try the new release of creamlinux (2.1.0) that just got published - that should resolve the important errors in your log. According to #11, the DLCs still did not work some time ago, but it's worth a try.

**Comment by Novattz** [comment]
Tried the newest version with ETS2 but from what i can tell it just tells me i have 0 dlcs. I have like 2 dlcs that i have actually purchased but they are no longer appearing when i try to unlock the rest with cream.

**Comment by anticitizn** [comment]
Hey @Novattz, sorry for the late response. If you still have the game installed, could you please provide the console logs (as shown in the readme)? Thanks in advance.

**Comment by anticitizn** [comment]
Closing this issue to consolidate the discussion in #11 - please continue there. :)
