### ISSUE TITLE
Not working for Total WarHammer 3 

### ISSUE THREAD

**Issue by myagizmaktav** [anticitizn/creamlinux#25]
I get this error.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
sh: 1: ./home/fox/.steam/debian-installation/steamapps/common/Total: not found
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
fox@fox-pc:~/.steam/debian-installation/steamapps/common/Total War WARHAMMER III$ 

Btw I add dlcs to cream api 
364360 = Total War: WARHAMMER
594570 = Total War: WARHAMMER II
2325830	= Total War: WARHAMMER III – Shadows of Change
1374300 = Total War: WARHAMMER III - Blood for the Blood God III
1670540 = Total War: WARHAMMER III - Ogre Kingdoms
1824060 = Total War: WARHAMMER III - Champions of Chaos
1834020 = Total War: WARHAMMER III - Chaos Warriors
1834021 = Total War: WARHAMMER III - Blood for the Blood God
1834022 = Total War: WARHAMMER III - Call of the Beastmen
1834023 = Total War: WARHAMMER III - The Grim and the Grave
1834024 = Total War: WARHAMMER III - Wurrzag
1834025 = Total War: WARHAMMER III - The King and the Warlord
1834026 = Total War: WARHAMMER III - Grombrindal The White Dwarf
1834027 = Total War: WARHAMMER III - Realm of The Wood Elves
1834030 = Total War: WARHAMMER III - Bretonnia
1834031 = Total War: WARHAMMER III - Isabella von Carstein
1834032 = Total War: WARHAMMER III - Krell
1834033 = Total War: WARHAMMER III - Norsca
1834034 = Total War: WARHAMMER III - 30th Anniversary Regiments
1834035 = Total War: WARHAMMER III - Jade Wizard
1834036 = Total War: WARHAMMER III - Grey Wizard
1834037 = Total War: WARHAMMER III - Rise of the Tomb Kings
1834038 = Total War: WARHAMMER III - Tretch Craventail
1834039 = Total War: WARHAMMER III - The Queen & The Crone
1834040 = Total War: WARHAMMER III - Steps of Isha
1834041 = Total War: WARHAMMER III - Alith Anar
1834042 = Total War: WARHAMMER III - Bone Giant
1834043 = Total War: WARHAMMER III - Curse of the Vampire Coast
1834044 = Total War: WARHAMMER III - Lokhir Fellheart
1834045 = Total War: WARHAMMER III - The Prophet & The Warlock
1834046 = Total War: WARHAMMER III - Tiktaq'to
1834047 = Total War: WARHAMMER III - Amethyst Wizard
1834048 = Total War: WARHAMMER III - The Hunter and the Beast
1834049 = Total War: WARHAMMER III - Gor-Rok
1834050 = Total War: WARHAMMER III - Gotrek & Felix
1834051 = Total War: WARHAMMER III - The Shadow & The Blade
1834052 = Total War: WARHAMMER III - Repanse de Lyonesse
1834053 = Total War: WARHAMMER III - The Warden & The Paunch
1834054 = Total War: WARHAMMER III - Imrik
1834055 = Total War: WARHAMMER III - Black Orc Big Boss
1834056 = Total War: WARHAMMER III - Catchweb Spidershrine
1834057 = Total War: WARHAMMER III – The Twisted & The Twilight
1834058 = Total War: WARHAMMER III - Skaven Chieftain
1834060 = Total War: WARHAMMER III – Glade Captain
1834061 = Total War: WARHAMMER III - Rakarth
1834062 = Total War: WARHAMMER III – The Silence & The Fury
1834063 = Total War: WARHAMMER III - Blood for the Blood God II
1834064 = Total War: WARHAMMER III - Thorek Ironbrow
1834065 = Total War: WARHAMMER III - Great Bray Shaman
1834066 = Total War: WARHAMMER III - Ogre Mercenaries
2059190 = chaosdwarf

**Comment by anticitizn** [comment]
This error suggests that spaces are not being handled properly somewhere, probably some missing quotation marks:
`sh: 1: ./home/fox/.steam/debian-installation/steamapps/common/Total: not found`, because the actual executable is probably called something like `Total War Warhammer III`. You used one of the launch parameters from the readme, right? I'm doing some testing right now, will report back in a bit.

**Comment by anticitizn** [comment]
I just tested and it appears that games with spaces in their name launch correctly for me using creamlinux, weird. Which launch parameters did you use exactly?

**Comment by myagizmaktav** [comment]
I use directly static path instead relative path.

**Comment by myagizmaktav** [comment]
And I try to ck3 either it give not permission error 

ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
sh: 1: ./cream.sh: Permission denied
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

**Comment by myagizmaktav** [comment]
Update I add sudo to command and 
I take this error either.

ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[sudo] password for fox: 
ERROR: ld.so: object '/tmp/lib64Creamlinux.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/tmp/libsteam_api.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/tmp/lib32Creamlinux.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
steam-launch-wrapper: $XDG_RUNTIME_DIR not set.
ERROR: ld.so: object '/tmp/lib32Creamlinux.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

**Comment by anticitizn** [comment]
> And I try to ck3 either it give not permission error

Try running `chmod +x ./cream.sh` in the directory, the script's execution permission isn't set apparently. Can you post your exact launch parameters, please?

**Comment by myagizmaktav** [comment]
![image](https://github.com/anticitizn/creamlinux/assets/115627863/95b92090-c9d4-42bf-bb5e-f58ade0e08da)
![image](https://github.com/anticitizn/creamlinux/assets/115627863/c4669d5c-a585-40b4-a4af-4ff7befd422d)
ck3 files

**Comment by myagizmaktav** [comment]
![image](https://github.com/anticitizn/creamlinux/assets/115627863/6e273dde-583b-42a0-9b3e-cf052a757ba5)
Stuck

**Comment by myagizmaktav** [comment]
If you wanna see live my discord id is `yagizm`

**Comment by myagizmaktav** [comment]
![image](https://github.com/anticitizn/creamlinux/assets/115627863/276c3993-124a-4439-9027-3d65bad76944)
This is warhammer 3 error.
![image](https://github.com/anticitizn/creamlinux/assets/115627863/eb1c42c3-4486-4431-a659-25c870e669b7)

**Comment by myagizmaktav** [comment]
@anticitizn 
I worked to warhammer and I get this error.

ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[sudo] password for fox: 
/home/fox/.steam/debian-installation/steamapps/common/Total War WARHAMMER III
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/tmp/lib64Creamlinux.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/tmp/libsteam_api.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/tmp/lib32Creamlinux.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/tmp/lib32Creamlinux.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/tmp/lib32Creamlinux.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/tmp/lib32Creamlinux.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 180325 != 180324, skipping destruction (fork without exec?)
pid 180328 != 180324, skipping destruction (fork without exec?)
pid 180332 != 180324, skipping destruction (fork without exec?)
pid 180331 != 180324, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/tmp/lib32Creamlinux.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/tmp/lib32Creamlinux.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/tmp/lib32Creamlinux.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/tmp/lib32Creamlinux.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/tmp/lib32Creamlinux.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
TotalWarhammer3: crash reporter initialised with path "/home/fox/.local/share/feral-interactive/Total War WARHAMMER III/crashes"
SDL2 initialised [built against 2.0.12, running with 2.0.12]
[S_API] SteamAPI_Init(): Loaded '/home/fox/.steam/debian-installation/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 1142710
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198056222632 [API loaded no]
ERROR: ld.so: object '/tmp/lib32Creamlinux.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[0219/184831.762742:ERROR:gpu_process_transport_factory.cc(1026)] Lost UI shared context.
Fossilize INFO: Overriding serialization path: "/home/fox/.steam/debian-installation/steamapps/shadercache/1142710/fozpipelinesv6/steamapprun_pipeline_cache".
[0219/184831.934243:INFO:CONSOLE(8672)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.", source: file:///home/fox/.steam/debian-installation/steamapps/common/Total%20War%20WARHAMMER%20III/share/FeralUI/Core/3rdParty/jquery-ui-1.10.4.custom/js/jquery-1.10.2.js (8672)
[0219/184831.941453:INFO:CONSOLE(0)] "Styling master document from stylesheets defined in HTML Imports is deprecated. Please refer to https://goo.gl/EGXzpw for possible migration paths.", source:  (0)
[0219/184831.967279:INFO:CONSOLE(6569)] "The specified value "!" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.", source: file:///home/fox/.steam/debian-installation/steamapps/common/Total%20War%20WARHAMMER%20III/share/FeralUI/Core/3rdParty/jquery-ui-1.10.4.custom/js/jquery-1.10.2.js (6569)
Opening in existing browser session.
Shutdown handler: initalize.
Shutdown handler: cleanup.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/fox/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

**Comment by myagizmaktav** [comment]
Its opening launher first and creamapi inject to launcher. not game I think.

**Comment by myagizmaktav** [comment]
fixed change to compatibility to proton and add cream api dll.

**Comment by anticitizn** [comment]
Hi, sorry for late response, got work :(

> Its opening launher first and creamapi inject to launcher. not game I think. You should add when app closing search pid to same folder location any process have.
Launchers have been known to cause some issues in the past, but creamlinux still works in all games with launchers that I've tried (Stellaris, HOI4, etc). Is there an option to skip the launcher? Some steam games offer a setting for this in their properties.


> fixed change to compatibility to proton and add cream api dll.
Did you make some additions to creamlinux locally? I would like to see them if you did (or open a pull request if you have time for it). Creamlinux isn't designed to work with proton, regular cream API should do just fine in that case.

**Comment by myagizmaktav** [comment]
Im adding creamapi dll(no .so file) to proton version.
![image](https://github.com/anticitizn/creamlinux/assets/115627863/d24c3b79-8727-48db-af2f-de7b7f3504b5)

And for ck 3 https://cs.rin.ru/forum/viewtopic.php?p=2990426#p2990426 you need the install dlc
and change steamapi dll to ck3 inside and paradox launcher inside.

**Comment by myagizmaktav** [comment]
about update creamapi V4.5 working on proton not working 5

**Comment by myagizmaktav** [comment]
update warhammer when you run from proton. its crash about 1 hour later but native not like that.
In native feral browser opening.

**Comment by myagizmaktav** [comment]
and can you delete issue pls.
