### ISSUE TITLE
CTA Gates of hell not working.

### ISSUE THREAD

**Issue by JustCauseWhyNot** [anticitizn/creamlinux#27]
I got this `ERROR: ld.so: object '/home/justcausewhynot/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/bin/sh: ./cream.sh: No such file or directory`. I've unziped cream-linux into the binaries folder where steam_api64 was already. I'm not sure why this is failing. 

```
 # add the dlc you want to fake here
# APPID = DLC Name
# copying a file from windows creamapi will not work, you need to fix line endings
# the DLC id's below are for HOI4
[config]
# if we should also list the DLCs you own and not just the ones on this list
issubscribedapp_on_false_use_real = true

[methods]
disable_steamapps_issubscribedapp = false
 
[dlc]
; DLC handling.
; Format: <dlc_id> = <dlc_description>
; e.g. : 247295 = Saints Row IV - GAT V Pack
; If the DLC is not specified in this section
; then it won't be unlocked
487170 = Call to Arms - Basic Edition
1911520 = Call to Arms - Gates of Hell: Talvisota
2123890 = Call to Arms - Gates of Hell: Scorched Earth
2447590 = Call to Arms - Gates of Hell: Liberation
```

**Comment by anticitizn** [comment]
Hi again, thanks for posting. Can you please please provide an overview of the game's directory (`ls` would be enough)? Creamlinux should be unpacked where the game's executable is located as the location of steam_api64 shouldn't make a difference now with the latest version of creamlinux. Since the creamlinux script can't be found when launching, I presume it is currently in the wrong folder.

**Comment by JustCauseWhyNot** [comment]
<details>
<summary> ~/common/Call\ to\ Arms \ -\ Gates\ of\ Hell/ </summary>

```
❯ ls -lf
.  ..  binaries  localizations  mods  resource
```

</details>

<details>
<summary> ~/common/Call\ to\ Arms \ -\ Gates\ of\ Hell/binaries/x64/ </summary>

```
❯ ls -lf
.                  call_to_arms.exe            icuin56.dll                  steam_appid.txt            lib32Creamlinux.so
..                 call_to_arms_ed.exe         icuio56.dll                  steam_startup_cta.txt      lib64Creamlinux.so
announcements.set  call_to_arms_server.exe     icuuc56.dll                  WaveWorks.win64.dll        cream_api.ini
bdcap64.dll        call_to_arms_workshop.exe   mss                          WaveWorks_debug.win64.dll
BsSndRpt64.exe     d3dcompiler_47.dll          mss64.dll                    WaveWorks_debug.win64.pdb
BugSplat64.dll     GFSDK_SSAO_D3D11.win64.dll  sdkencryptedappticket64.dll  xvidcore.dll
BugSplatRc64.dll   icudt56.dll                 steam_api64.dll              cream.sh
```

</details>

**Comment by anticitizn** [comment]
My bad, I missed this. Gates of Hell has no native Linux port as far as I know so you must be playing it through Proton. Creamlinux doesn't work through Proton, but as far as I know regular creamAPI/smokeAPI does.

**Comment by JustCauseWhyNot** [comment]
Oh. I'll try that then. I didn't realize. Thank you for your help.
