### ISSUE TITLE
Is this for native games, or does it work while using proton?

### ISSUE THREAD

**Issue by NL-TCH** [anticitizn/creamlinux#31]
**CK3**: 

**Issue**:
- [X] Game does not launch
- [  ] Game launches but DLCs are not enabled

**Logs**:
Error: libsteam_api.so not found.

(this is the only log i get (playing with GEproton 7.55))

Game works without prefix

**Game Directory*:
total 11M
drwxrwx--- 1 tch tch  560 30 mrt 20:30 binaries
drwxrwx--- 1 tch tch   88  3 feb 20:48 clausewitz
-rwxr-xr-x 1 tch tch   20 28 mrt 19:47 clausewitz_branch.txt
-rwxr-xr-x 1 tch tch   40 28 mrt 19:47 clausewitz_rev.txt
-rwxrwx--- 1 tch tch  17K  1 feb 12:56 cream_api.ini
-rwxrwx--- 1 tch tch 1,1K  1 feb 12:56 cream.sh
drwxrwx--- 1 tch tch 1,3K 20 mrt 22:47 game
drwxrwx--- 1 tch tch  124  3 feb 20:48 jomini
drwxrwx--- 1 tch tch  334 30 mrt 20:30 launcher
-rwxrwx--- 1 tch tch 3,2M  1 feb 12:56 lib32Creamlinux.so
-rwxrwx--- 1 tch tch 3,5M  1 feb 12:56 lib64Creamlinux.so
-rw-r--r-- 1 tch tch 3,4M 30 mrt 20:40 SmokeAPI64.dll
-rwxr-xr-x 1 tch tch   14 28 mrt 19:47 titus_branch.txt
-rwxr-xr-x 1 tch tch   40 28 mrt 19:47 titus_rev.txt
binaries/:
total 120M
-rwxr-xr-x 1 tch tch 406K  5 feb 15:43 bink2w64.dll
-rwxr-xr-x 1 tch tch  73M 28 mrt 19:47 ck3.exe
-rwxr-xr-x 1 tch tch  145  5 feb 15:43 ck3.exe.manifest
drwxrwx--- 1 tch tch   16  3 feb 20:48 crash_reporter
-rwxr-xr-x 1 tch tch 384K  5 feb 15:43 cudart64_30_14.dll
-rwxr-xr-x 1 tch tch 4,3M  5 feb 15:43 d3dcompiler_47.dll
-rwxr-xr-x 1 tch tch 1,9M  5 feb 15:43 dbghelp.dll
-rwxr-xr-x 1 tch tch  20M  5 feb 15:43 dxcompiler.dll
-rwxr-xr-x 1 tch tch 1,5M  5 feb 15:43 dxil.dll
-rwxr-xr-x 1 tch tch 1,8M  5 feb 15:43 fmod.dll
-rwxr-xr-x 1 tch tch 1,5M  5 feb 15:43 fmodstudio.dll
-rwxr-xr-x 1 tch tch 125K  5 feb 15:43 jpeg62.dll
-rwxr-xr-x 1 tch tch 158K  5 feb 15:43 libpng12.dll
-rwxr-xr-x 1 tch tch 368K  5 feb 15:43 libtiff3.dll
-rwxr-xr-x 1 tch tch 1,1M  5 feb 15:43 msvcp80.dll
-rwxr-xr-x 1 tch tch 778K  5 feb 15:43 msvcr80.dll
-rwxr-xr-x 1 tch tch 5,5M  5 feb 15:43 nakama-cpp.dll
-rwxr-xr-x 1 tch tch 323K  5 feb 15:43 nvtt.dll
-rwxr-xr-x 1 tch tch 5,1M  5 feb 15:43 pops_api.dll
-rwxr-xr-x 1 tch tch 282K  5 feb 15:43 steam_api64.dll
-rwxrwx--- 1 tch tch    7  3 feb 21:04 steam_appid.txt
-rw-r--r-- 1 tch tch 2,9M 30 mrt 20:40 version.dll
-rwxr-xr-x 1 tch tch  74K  5 feb 15:43 zlib1.dll

clausewitz/:
total 4,0K
-rwxrwx--- 1 tch tch 1,1K  3 feb 21:04 compound_settings.txt
drwxrwx--- 1 tch tch   66  3 feb 20:48 fonts
drwxrwx--- 1 tch tch  252  3 feb 20:48 gfx
drwxrwx--- 1 tch tch  474  3 feb 20:48 gui
drwxrwx--- 1 tch tch 2,9K  3 feb 20:48 localization

game/:
total 62M
-rwxrwx--- 1 tch tch 2,4K  3 feb 21:05 arrow_bar.dds
-rwxrwx--- 1 tch tch  380  3 feb 21:04 checksum_manifest.txt
-rwxrwx--- 1 tch tch 2,3K  3 feb 21:04 colors.tga
drwxrwx--- 1 tch tch 3,0K  4 mrt 18:58 common
-rwxrwx--- 1 tch tch 3,4K  3 feb 21:04 compound_settings.txt
drwxrwx--- 1 tch tch   38  3 feb 20:49 content_source
-rwxr-xr-x 1 tch tch 2,2K  4 mrt 18:37 credit_portraits.txt
-rwxr-xr-x 1 tch tch  93K  7 mrt 17:33 credits.txt
-rwxrwx--- 1 tch tch 3,6M  3 feb 21:04 d3dcompiler_47.dll
drwxrwx--- 1 tch tch  550  4 mrt 18:58 data_binding
-rwxrwx--- 1 tch tch 963K  3 feb 21:04 dbghelp.dll
drwxrwx--- 1 tch tch   50  3 feb 20:48 dlc
drwxrwx--- 1 tch tch   74  4 mrt 18:58 dlc_metadata
drwxrwx--- 1 tch tch 2,0K 28 mrt 19:47 events
drwxrwx--- 1 tch tch  224  3 feb 20:49 fonts
drwxrwx--- 1 tch tch  262  3 feb 20:49 gfx
drwxrwx--- 1 tch tch 8,1K 28 mrt 19:47 gui
drwxrwx--- 1 tch tch  230  3 feb 20:49 history
-rwxrwx--- 1 tch tch 447K  3 feb 21:04 libsteam_api.dylib
-rwxrwx--- 1 tch tch 3,6M  3 feb 21:04 libSteam.dylib
-rwxrwx--- 1 tch tch 1,3M  3 feb 21:04 libtbb_debug.dylib
-rwxrwx--- 1 tch tch 526K  3 feb 21:04 libtbb.dylib
-rwxrwx--- 1 tch tch 361K  3 feb 21:04 libtier0_s.dylib
-rwxrwx--- 1 tch tch 470K  3 feb 21:04 libvstdlib_s.dylib
drwxrwx--- 1 tch tch   26  3 feb 20:48 licenses
drwxrwx--- 1 tch tch  140  3 feb 20:49 localization
-rwxr-xr-x 1 tch tch 7,0K 20 mrt 22:45 log_settings_debug.json
-rwxr-xr-x 1 tch tch 7,0K 20 mrt 22:45 log_settings_live.json
-rwxr-xr-x 1 tch tch 6,9K 20 mrt 22:45 log_settings_release.json
-rwxrwx--- 1 tch tch   19  3 feb 21:04 manifest.json
drwxrwx--- 1 tch tch  442  3 feb 20:49 map_data
-rwxrwx--- 1 tch tch    5  3 feb 21:04 mask_painter_meta.json
drwxrwx--- 1 tch tch   62  4 mrt 18:58 music
drwxrwx--- 1 tch tch   16  3 feb 20:49 notifications
-rwxrwx--- 1 tch tch  370  3 feb 21:04 paths_checksummed.settings
-rwxrwx--- 1 tch tch 1,6K  3 feb 21:04 paths.settings
-rwxr-xr-x 1 tch tch 3,5K  4 mrt 18:37 settings_layout.txt
drwxrwx--- 1 tch tch   56  3 feb 20:49 sound
-rwxrwx--- 1 tch tch 184K  3 feb 21:04 steam_api.dll
-rwxrwx--- 1 tch tch 6,9M  3 feb 21:04 steamclient.dll
-rwxrwx--- 1 tch tch  40M  3 feb 21:04 steamclient.dylib
-rwxrwx--- 1 tch tch 2,8M  3 feb 21:04 Steam.dll
-rwxrwx--- 1 tch tch 244K  3 feb 21:04 tbb_debug.dll
-rwxrwx--- 1 tch tch 140K  3 feb 21:04 tbb.dll
-rwxrwx--- 1 tch tch  37K  3 feb 21:04 tbbmalloc.dll
-rwxrwx--- 1 tch tch  25K  3 feb 21:04 tbbmalloc_proxy.dll
drwxrwx--- 1 tch tch  814  4 mrt 18:58 tests
-rwxrwx--- 1 tch tch 238K  3 feb 21:04 tier0_s.dll
drwxrwx--- 1 tch tch  120  4 mrt 18:58 tools
drwxrwx--- 1 tch tch   24  3 feb 20:48 tweakergui_assets
-rwxrwx--- 1 tch tch 215K  3 feb 21:04 vstdlib_s.dll

jomini/:
total 4,0K
drwxrwx--- 1 tch tch  128  3 feb 20:48 common
drwxrwx--- 1 tch tch  254  3 feb 20:48 gfx
drwxrwx--- 1 tch tch  770  4 mrt 18:58 gui
drwxrwx--- 1 tch tch    6  3 feb 20:48 jomini
drwxrwx--- 1 tch tch  592  3 feb 20:48 localization
drwxrwx--- 1 tch tch   66  3 feb 20:48 notifications
-rwxrwx--- 1 tch tch 1,3K  3 feb 21:05 settings_layout.txt

launcher/:
total 240M
drwxrwx--- 1 tch tch  244  3 feb 20:48 assets
-rwxr-xr-x 1 tch tch 7,5M 20 mrt 22:46 dowser.exe
-rwxrwx--- 1 tch tch 109M  3 feb 21:05 launcher-installer-windows_2023.8.1.msi
-rwxr-xr-x 1 tch tch 121M 20 mrt 22:47 launcher-installer-windows_2024.4.msi
-rwxr-xr-x 1 tch tch 1,3K 28 mrt 19:47 launcher-settings.json
-rwxr-xr-x 1 tch tch 3,5K  5 feb 15:43 settings-layout.json
-rwxr-xr-x 1 tch tch  55K  5 feb 15:43 ThirdPartyLicenses.txt
-rw-r--r-- 1 tch tch 2,9M 30 mrt 20:40 version.dll

**Comment by anticitizn** [comment]
Hi, it only works for native apps. For proton apps you can use the regular windows-based SmokeAPI - unsure how installing it on proton works exactly but people have gotten it to work.

**Comment by Facni** [comment]
@NL-TCH you can use https://github.com/prismatica-dev/DLCUnlockerScript

**Comment by anticitizn** [comment]
@Facni as far as I see, this is more or less an installation script that installs SmokeAPI if running through Proton, and standard `creamlinux` if running on native Linux. It's convenient, but since it includes compiled binaries of creamlinux and SmokeAPI instead of fetching the newest versions and compiling them on the spot, the versions that it it installs will likely be outdated. This might be fine for now, but it might also break sometime in the future. Just FYI.

**Comment by anticitizn** [comment]
Closing as not planned, use regular SmokeAPI if you're using Proton
