### ISSUE TITLE
Euro Truck Simulator 2 Not Starting

### ISSUE THREAD

**Issue by MaxiTornado** [anticitizn/creamlinux#35]
**Euro Truck Simulator 2**: 

**Issue**:
- [ x ] Game does not launch
- [  ] Game launches but DLCs are not enabled

**Logs**:
Please provide the complete logs according to instructions in the [readme](https://github.com/anticitizn/creamlinux/blob/master/README.md):

ERROR: ld.so: object '/home/erik/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/usr/bin/sh: ./cream.sh: No such file or directory

**Game Directory*:
Please provide an overview of your game directory using `ls -lh; ls -lh */`:

[ets2.txt](https://github.com/user-attachments/files/15843800/ets2.txt)

**Additional Information**:
I press play, it displays the cancel button for a moment, then goes back to play.

**Comment by anticitizn** [comment]
Hi, are you using the latest version of creamlinux? Weird that it doesn't find the script, it is right there. Even so, several people have reported that creamlinux doesn't work on ETS 2 (as in it launches, but does not unlock the DLCs). #11 for reference - please continue the issue there, going to close this to keep the discussion more concentrated (there's 3 separate issues at the moment).
