### ISSUE TITLE
Cannot Install DLC for Civlization VI

### ISSUE THREAD

**Issue by rek3000** [anticitizn/creamlinux#36]
I try to install DLCs for Civilization VI, but it is not work. If you have time, please take a look
Folder directory: [rek@basement Sid Meier's Civilization VI]$ ls -lh; ls -lh */,
total 6.7M
drwxr-xr-x 1 rek rek  140 Jul  4 23:09 2KLauncher
drwxr-xr-x 1 rek rek   76 Jul  4 23:09 Base
-rw-r--r-- 1 rek rek  710 Jul  6 17:23 cream_api.ini
-rwxr--r-- 1 rek rek 1.1K Jul  6 17:23 cream.sh
drwxr-xr-x 1 rek rek   16 Jul  4 23:08 CTP
drwxr-xr-x 1 rek rek  900 Jul  4 23:09 Debug
drwxr-xr-x 1 rek rek  788 Jul  4 23:09 DLC
drwxr-xr-x 1 rek rek 5.2K Jul  4 23:41 LaunchPad
-rw-r--r-- 1 rek rek 3.2M Jul  6 17:23 lib32Creamlinux.so
-rw-r--r-- 1 rek rek 3.5M Jul  6 17:23 lib64Creamlinux.so
drwxr-xr-x 1 rek rek    6 Jul  4 23:09 steamassets
ls: cannot access '*/,': No such file or directory

Here is the log:
Error: libsteam_api.so not found.

Another thing: I need to use wine to run because the Linux version is not up-to-date

**Comment by anticitizn** [comment]
Hello, creamlinux does not work with wine or Proton. It's only for native Steam games. I will make this more clear in the readme.

Since you are using wine anyway, you can just use regular SmokeAPI for the DLCs. I'm not sure how to install that with wine, but people have gotten it to work.

**Comment by rek3000** [comment]
Thanks for clarifying. I have tried to use AutoCreamAPI, and it worked!

**Comment by anticitizn** [comment]
Great! Was it much of a hassle to get it working on Wine? Others have asked about this but I haven't tried it myself, so it would be nice to have a very quick overview of the setup process on wine.

**Comment by rek3000** [comment]
Using Wine/Proton on Steam is pretty simple, there is an application that auto detect your steam game which I used is AutoCreamAPI (Install .NetCore3 for Wine to work), and the later process is easy to do as instructions. CreamAPI is not work on Linux, so I have to use another app like AutoCreamAPI (https://github.com/MoebiusZero/AutoCreamAPI) which let user choose steamapi lib file and the install DLC process is a cup of tea .
