### ISSUE TITLE
Paradox games don't launch when creamlinux is enabled

### ISSUE THREAD

**Issue by Tom-Dude** [anticitizn/creamlinux#42]
I installed creamlinux manually, and filled out the missing DLC using info from steamdb. I pasted the given launch option into each game's launch options, and confirmed all DLC content is present for each game. I also attempted this with the installer (dlc_fetcher.py) to no avail.

When I try to start the game, it doesn't launch (play button goes right back to play). I tried the solution given in the FAQ, but even after confirming each copy of cream.sh is executable, the games still do not run. Below is my log using the command ```ls -lh; ls -lh */```:

https://pastebin.com/xftuxgtT

EDIT: I am using Linux Mint 22 with the .deb install of steam, if that helps.

**Comment by anticitizn** [comment]
Unfortunately I can't replicate this. Playing on Linux Mint 22, CK2 3.3.5.1 with creamlinux installed through Novattz's installer and Steam from `.deb`. It launches and works perfectly fine for me.

Can you please follow the `Gathering Logs` section in the readme and report back? Just set your launch parameter to `gnome-terminal -- sh -c "./cream.sh %command%; exec bash"` and post the resulting logs here in their entirety. Thanks in advance!

**Comment by Tom-Dude** [comment]
I gave up on it, since I don't use that device often anyways. Is it alright if this issue can be deleted?

**Comment by anticitizn** [comment]
I will just close the issue if you don't mind, but if you don't want it showing up on your profile or something, deleting it is okay too. Thanks for reporting nevertheless!
