### ISSUE TITLE
Crusader Kings 3 can't detect cream.sh

### ISSUE THREAD

**Issue by vannotz** [anticitizn/creamlinux#8]
I tried with both CK3 and HOI4, and CK3 is the only one with this issue, the game won't even launch and the logs output 
```
ERROR: ld.so: object '/home/$USER/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
sh: 0: cannot open ./cream.sh: No such file
```

**Comment by anticitizn** [comment]
All the creamlinux files should be located at the game's base directory (so in `/home/.../Crusader Kings III/`, not in the `binaries` folder). Then try to edit the path to `libsteam_api.so` in the `cream.sh` script like this:

```
#!/bin/bash
cp "$PWD/lib32Creamlinux.so" /tmp/lib32Creamlinux.so
cp "$PWD/lib64Creamlinux.so" /tmp/lib64Creamlinux.so
cp "$PWD/binaries/libsteam_api.so" /tmp/libsteam_api.so
LD_PRELOAD="$LD_PRELOAD /tmp/lib64Creamlinux.so /tmp/lib32Creamlinux.so /tmp/libsteam_api.so" "$@"
EXITCODE=$?
rm /tmp/lib32Creamlinux.so
rm /tmp/lib64Creamlinux.so
rm /tmp/libsteam_api.so
exit $EXITCODE
```

See if that works. In the meantime I'll update the launch script to automatically find `libsteam_api.so` wherever it is in the game's directory, apparently a lot of games do it.

**Comment by vannotz** [comment]
It launches without problem now, thank you.

**Comment by anticitizn** [comment]
Glad to hear! Do the DLCs work as well?

**Comment by vannotz** [comment]
I haven't tried, it seems the uploaders haven't caught up to the newest one, and I have all previous ones. I'll give you a heads up whenever I'm able to test it

**Comment by vannotz** [comment]
It works perfectly, thank you for your work.

**Comment by anticitizn** [comment]
Thank you too for testing and bringing the `libsteam_api.so` thing to my attention!
